package org.dmd.mvw.client.mvw;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.Place;

/**
 * The MvwPlace extends the base Place and provides a useful interface for code that's
 * generated by the Model View Whatever framework. For instance, it indicates that any
 * given Place knows the Activity that runs in it. 
 */
abstract public class MvwPlace extends Place {

	/**
	 * Derived generated code will instantiate 
	 * @return
	 */
	abstract Activity getActivity();
}
