package org.dmd.features.extgwt.client;

import com.extjs.gxt.ui.client.event.EventType;

/**
 * The ApplicationIF interface defines the interface to an overall application
 * that uses the ExtGWT MVC framework. The interface is implemented by the 
 * class that's generated by the MVC Generator Utility.
 * <P>
 * One of the primary reasons for the existence of the interface is to allow for
 * code modularity when using the MVC framework. This mechanism is required because
 * the EventType instances used by the framework must be defined in a monolithic
 * way; they rely on a globally unique ID.
 * <P>
 * The ApplicationIF allows generated Controllers and Views to get handles to
 * the unique EventTypes by name (this is done in their constructors). By doing
 * this, we allow MVC modules to be defined separately and brought together to 
 * form an overall application.
 */
public interface ApplicationIF {

	/**
	 * This method must be overloaded to return the globally unique EventType
	 * for a given name. The names are the names of MvcEvent definitions.
	 * @param eventName The name of the event.
	 * @return The globally unique EventType instance.
	 */
	abstract public EventType getEvent(String eventName);
}
